train: /data/ephemeral/home/dataset/train/  # 학습 이미지 경로
val: /data/ephemeral/home/dataset/test/    # 검증 이미지 경로

# 클래스 수
nc: 10  # 클래스의 수 (여러 클래스가 있는 경우)

# 클래스 이름
names: ['general_trash','paper','paper_pack','metal','glass','plastic','styrofoam','plastic_bag','battery','clothing']  # 클래스 이름 추가