# 학습, 검증 데이터 경로
train: /data/ephemeral/home/dataset/train/
val: /data/ephemeral/home/dataset/test/

# 클래스 수
nc: 10  # 10개의 클래스

# 클래스 이름
names:
  - general_trash
  - paper
  - paper_pack
  - metal
  - glass
  - plastic
  - styrofoam
  - plastic_bag
  - battery
  - clothing